require (ggplot2)
require (gridExtra)

plot.data <- read.table ("complement_protein_immune_data_together.txt", sep = "\t", header = TRUE)
plot.data$Group <- factor (plot.data$Group, levels = c ("Feat", "Rest", "WT"), labels = c ("Region", "Other", "WT"))
plot.data$Name <- factor (plot.data$Name, levels = c ("Thrombin", "C2", "Plasminogen"))
plot.3.genes <- ggplot (plot.data, aes (x = Name, y = Score)) + geom_boxplot (aes(color = Group), outlier.shape = NA, position = position_dodge ()) + geom_point (position=position_jitterdodge(jitter.width = 0.2), aes (fill = Group, color = Group, alpha = Group, size = Group), shape = 21) + scale_alpha_manual (values = c (1,1,0.1)) + scale_fill_manual (values = c ("#FF6600", "#E1D4C0", "lightgray")) + scale_color_manual (values = c ("#FF6600", "#E1D4C0", "lightgray")) + scale_size_manual (values = c (2,2,0.5)) + theme (axis.text = element_text (color = "black"), axis.ticks = element_line (color = "black"), axis.line = element_line (color = "black"), panel.background = element_blank(), legend.position = "none", axis.title = element_blank(), axis.title.y = element_text (face = "italic")) + geom_vline (xintercept = 1.5, linetype = 2) + ylim (-2500, 3500)

sub.th <- subset (plot.data, Name == "Thrombin")
sub.th$Group <- factor (sub.th$Group, levels = c ("Region", "Other", "WT"), labels = c ("Trypsin", "Other", "WT"))
plot.coords <- ggplot (subset (sub.th, Gene != "WT"), aes (x = Pos, y = Score)) + geom_point (aes (color = Group)) + scale_color_manual (values = c ("#FF6600", "#E1D4C0", "lightgray")) + scale_size_manual (values = c (2,2,0.5)) + theme (axis.text = element_text (color = "black"), axis.ticks = element_line (color = "black"), axis.line = element_line (color = "black"), panel.background = element_blank(), legend.position = "none", axis.title = element_blank(), axis.title.y = element_text (face = "italic")) + geom_vline (xintercept = 364, linetype = 2) + geom_vline (xintercept = 613, linetype = 2) + ylim (-2500, 3500)

gene.plot <- ggplot () + geom_boxplot (data = subset (sub.th, Group != "WT"), aes (x = "Thrombin", y = Score), outlier.shape = NA) + geom_point (data = subset (sub.th, Group != "WT"), aes (x = "Thrombin", y = Score, color = Group), position = position_jitter (width = 0.2)) + geom_boxplot (data = subset (sub.th, Group == "WT"), aes (x = "WT", y = Score), outlier.shape = NA, color = "lightgray") + geom_point (data = subset (sub.th, Group == "WT"), aes (x = "WT", y = Score), position = position_jitter (width = 0.2), color = "lightgray", alpha = 0.3, size = 0.5) + theme (axis.text = element_text (color = "black"), axis.ticks = element_line (color = "black"), axis.line = element_line (color = "black"), panel.background = element_blank(), legend.position = "none", axis.title.x = element_blank(), axis.title.y = element_text (face = "italic")) + ylab ("ESTIMATE\nimmune score\n") + scale_color_manual (values = c ("#FF6600", "#E1D4C0"))
plot.th <- ggplot (sub.th, aes (x = Group, y = Score)) + geom_boxplot (aes(color = Group), outlier.shape = NA, position = position_dodge ()) + geom_point (position=position_jitter(width = 0.2), aes (fill = Group, color = Group, alpha = Group, size = Group), shape = 21) + scale_alpha_manual (values = c (1,1,0.1)) + scale_fill_manual (values = c ("#FF6600", "#E1D4C0", "lightgray")) + scale_color_manual (values = c ("#FF6600", "#E1D4C0", "lightgray")) + scale_size_manual (values = c (2,2,0.5)) + theme (axis.text = element_text (color = "black"), axis.ticks = element_line (color = "black"), axis.line = element_line (color = "black"), panel.background = element_blank(), legend.position = "none", axis.title = element_blank(), axis.title.y = element_text (face = "italic")) + ylim (-2500, 3500)
other.plot <- ggplot (subset (plot.data, Name != "Thrombin"), aes (x = Group, y = Score)) + geom_boxplot (aes(color = Group), outlier.shape = NA, position = position_dodge ()) + geom_point (position=position_jitter(width = 0.2), aes (fill = Group, color = Group, alpha = Group, size = Group), shape = 21) + scale_alpha_manual (values = c (1,1,0.1)) + scale_fill_manual (values = c ("#FF6600", "#E1D4C0", "lightgray")) + scale_color_manual (values = c ("#FF6600", "#E1D4C0", "lightgray")) + scale_size_manual (values = c (2,2,1)) + theme (axis.text = element_text (color = "black"), axis.ticks = element_line (color = "black"), axis.line = element_line (color = "black"), panel.background = element_blank(), legend.position = "none", axis.title.x = element_blank(), axis.title.y = element_text (face = "italic")) + ylim (-2500, 3500) + facet_wrap (~Name, ncol = 1) + ylab ("ESTIMATE\nimmune score\n") + theme (strip.text = element_text (face = "bold"), strip.background = element_blank())

figure.4 <- arrangeGrob (gene.plot, plot.coords, plot.th, other.plot, nrow = 2, ncol = 3, heights = c (3/10, 6/10))

ggsave (file = "Figure_4.pdf", figure.4)